# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wooseong Jung
title: Blockchain Developer & Devops Engineer
email: dntjd1097@gmail.com
website: www.github.com/dntjd1097

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: dntjd1097
instagram_username: wooseong0203
additional_links:
  - title: MKV.one
    icon: fas fa-globe
    url: https://mkv.one

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  Hello. My name is <b>Wooseong Jung<b> <br>I am a blockchain developer and a DevOps engineer. <br>Currently, I am a validator under the names MKV.one for projects such as Kava, E-money, Konstellation, and Odin.
  <br>I am most skilled in: <mark>Python</mark> , <mark>Ubuntu</mark> and <mark>bots</mark> on Discord, Telegram, Slack

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: MKV.one
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: mkv.one
        caption: 2021.10.06 ~ ing
        description: |
          ## I am operating as a solo validator for Cosmos-based chains.<br><br>
          ## Chains 
            - Band Protocol
              - Activate validator : 2021.10.06 ~ 2023.07.13
              - Activate Yoda : 2021.10.06 ~ 2023.07.13
            - e-Money
              - Activate validator : 2021.10.17 ~ ing
            - Kava
              - Activate validator : 2021.10.31 ~ ing
              - Activate relayor : 2022.03.19 ~ ing
            - Konstellation
              - Activate validator : 2022.02.28 ~ ing
            - Odin Protocol
              - Activate validator : 2022.03.20 ~ ing
              - Activate Yoda : 2022.03.20 ~ ing 
            - Osmosis
              - Activate relayor : 2022.03.19 ~ ing
            - Terra Classic
              - Activate relayor : 2022.03.19 ~ 2022.08.04
            - Archway 
              - Activate Torii testnet validator : 2022.03 ~ 2022.04

          <br><br>
          ## Technologies Used 
            - Frontend : <mark>React</mark>
            - Backend : <mark>Python</mark> , <mark>Golang</mark> , <mark>node.js</mark>
            - DB : <mark>MySQL</mark>
            - Monitoring : <mark>Telegram</mark> , <mark>Discord</mark> , <mark>Grafana</mark> , <mark>Tenderduty</mark> , <mark>PM2</mark> , <mark>PagerDuty</mark>
            - OS : <mark>Linux</mark> , <mark>Microsoft Windows</mark> , <mark>macOS</mark>
            - Server : <mark>OVH</mark> , <mark>AWS</mark>
            - Tools : <mark>Git</mark> , <mark>Notion</mark>

      - layout: left
        title: Google Developer Student Club (GDSC DJU)
        link: gdscdju.dev
        caption: 2023.01 ~ ing
        description: |
          ## Contributions 
            - Slack Bot 
              - Wakatime bot : 2023.03.05 ~ ing 
              - Calendar reminder bot with Notion : 2023.04.23 ~ ing 
              - Palm chat bot : 2023.06.17 ~ ing
              - Discord & Slack sync Bot : 2023.08.02 ~ ing
            - Discord Bot
              - Discord & Slack sync Bot : 2023.08.02 ~ ing
            - Frontend 
              - GDSC teddy website : 2023.03.10 ~ ing

          <br><br>
          ## Technologies Used 
            - Frontend : <mark>React</mark>
            - Backend : <mark>Python</mark>
            - DB : <mark>MySQL</mark>
            - Monitoring : <mark>Grafana</mark>
            - OS : <mark>Linux</mark> , <mark>Microsoft Windows</mark> , <mark>macOS</mark>
            - Server : <mark>Oracle</mark>
            - Tools : <mark>Git</mark> , <mark>Discord</mark> , <mark>Slack</mark> , <mark>Notion</mark>
  - title: Education
    layout: list
    content:
      - layout: left
        title: UNIVERSITY OF DAEJIN
        caption: 2019.03 ~ ing
        description: |
          ## Department of Computer Engineering
          - Data Structure, Algorithm , etc..
          - Philippine language training : 2019.08 , 2020.02

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
